fix: upgrade @types/bl (#17)
The types in this module import from `"bl/BufferList"` - types were
only added for the deep import in `@types/bl@5.x.x` so upgrade to
that version of the module, otherwise consuming modules without
`skipLibCheck` enabled see errors like:

```
node_modules/it-length-prefixed/dist/src/types.d.ts:3:29 - error TS7016: Could not find a declaration file for module 'bl/BufferList'. '/Users/alex/Documents/Workspaces/ipfs/js-ipfs-bitswap/node_modules/bl/BufferList.js' implicitly has an 'any' type.
  If the 'bl' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/bl`

3 import BufferList = require("bl/BufferList");
                              ~~~~~~~~~~~~~~~
```